apiVersion: v1
kind: ReplicationController
metadata:
  name: go
spec:
  replicas: 1
  selector:
    app: go
  template:
    metadata:
      name: go
      labels:
        app: go
    spec:
      containers:
      - name: go
        image: gcr.io/jntlserv0/godocker:v10
        ports:
        - containerPort: 8080
